import streamlit as st
import librosa
import numpy as np
import json
import tempfile
import os
import zipfile
import io
import requests
import random
import string
import google.generativeai as genai

# 1. Gemini API Setup
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
model = genai.GenerativeModel('gemini-2.5-flash')

st.set_page_config(page_title="ADOFAI AI Generator", page_icon="🧊")
st.title("🧊 얼불춤(ADOFAI) URL 자동 생성기")
st.write("음원 분석 후 서버에 업로드하여 다이렉트 URL을 발급합니다.")

uploaded_file = st.file_uploader("음악 파일 업로드", type=None)

if uploaded_file is not None:
    st.info("🎵 오디오 분석 및 패키지 생성 중...")
    
    with st.spinner("처리 중..."):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp_file:
            tmp_file.write(uploaded_file.read())
            tmp_file_path = tmp_file.name

        try:
            # Audio Analysis & AI Settings
            y, sr = librosa.load(tmp_file_path)
            onset_frames = librosa.onset.onset_detect(y=y, sr=sr)
            onset_times = librosa.frames_to_time(onset_frames, sr=sr)
            
            tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
            bpm_value = float(tempo[0]) if isinstance(tempo, np.ndarray) else float(tempo)
            
            angle_data = [0]
            for i in range(1, len(onset_times)):
                time_diff = onset_times[i] - onset_times[i-1]
                if time_diff < (60 / bpm_value) * 0.5:
                    angle_data.append(90)
                else:
                    angle_data.append(0)

            prompt = f"""
            너는 A Dance of Fire and Ice 맵 디자이너야.
            BPM {bpm_value:.1f}의 곡에 어울리는 맵 배경색과 트랙 색상을 JSON으로 짜줘.
            반드시 아래 4개의 키만 포함된 순수 JSON 객체 하나만 출력해:
            "trackColor", "backgroundColor", "bgImage", "hitsound"
            """
            response = model.generate_content(prompt)
            ai_settings_text = response.text.replace("```json", "").replace("```", "").strip()
            
            try:
                ai_settings = json.loads(ai_settings_text)
            except:
                ai_settings = {"trackColor": "ff0000", "backgroundColor": "000000"}

            audio_filename = uploaded_file.name

            settings_block = {
                "version": 11,
                "artist": "AI",
                "song": audio_filename,
                "author": "ADOFAI Generator",
                "separateCountdownTime": True,
                "previewImage": "",
                "previewIcon": "",
                "previewIconColor": "0082ba",
                "previewSongStart": 0,
                "previewSongDuration": 10,
                "seizureWarning": False,
                "levelDesc": "Generated by AI",
                "levelTags": "",
                "artistPermission": "",
                "artistLinks": "",
                "syncTrack": 0,
                "timeSignature": 4,
                "volume": 100,
                "overlayColor": "000000",
                "layer1Image": "",
                "layer1Position": [0, 0],
                "layer1Size": [100, 100],
                "bpm": bpm_value,
                "offset": 0,
                "pitch": 100,
                **ai_settings
            }

            settings_json = json.dumps(settings_block, ensure_ascii=False)
            angle_json = json.dumps(angle_data)
            
            adofai_str = f"""{{
    "angleData": {angle_json},
    "settings": {settings_json},
    "actions": [],
    "decorations": []
}}"""

            # Create ZIP archive in memory
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
                zip_file.writestr("level.adofai", adofai_str)
                uploaded_file.seek(0)
                zip_file.writestr(audio_filename, uploaded_file.read())

            st.success("✨ 맵 완성! Unity 엔진 호환 서버로 링크 생성 중...")

            # Filebin 서버로 업로드 (게임 엔진 다운로드 차단 회피)
            bin_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=12))
            safe_filename = "AI_Map_Package.zip" # 인코딩 에러 방지를 위해 영어로 고정
            upload_url = f"https://filebin.net/{bin_id}/{safe_filename}"
            
            headers = {"Content-Type": "application/zip"}
            upload_res = requests.post(upload_url, data=zip_buffer.getvalue(), headers=headers)
            
            # Filebin은 업로드 성공 시 201 Created를 반환함
            if upload_res.status_code == 201:
                download_link = upload_url
                st.write("### 🔗 얼불춤(ADOFAI) 다이렉트 URL:")
                st.code(download_link, language="text")
                st.write("이 링크를 복사해서 얼불춤에 그대로 붙여넣으면 다운로드 에러가 안 날 거야!")
            else:
                st.error(f"서버 업로드에 실패했어. 상태 코드: {upload_res.status_code}")

            # Backup manual download
            st.download_button(
                label="📦 혹시 모르니 수동 다운로드(.zip)",
                data=zip_buffer.getvalue(),
                file_name=f"AI_{audio_filename}.zip",
                mime="application/zip"
            )

        except Exception as e:
            st.error(f"Error occurred: {e}")
        finally:
            os.remove(tmp_file_path)
