plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.hoonex.adofai.exporter'
    compileSdk 35

    defaultConfig {
        applicationId 'dev.hoonex.adofai.exporter'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
